### PR TITLE
Copy watcher from common

### PR DESCRIPTION
**Pull request by prankulmahajan**
PR does the following,

1.Copy [watcher](https://github.com/IBM/ibm-csi-common/tree/master/pkg/watcher) and [metadata](https://github.com/IBM/ibm-csi-common/tree/master/pkg/metadata) to this library so as to remove dependency of `ibmcloud-volume-vpc` in go.mod of `ibm-vpc-block-csi-driver`
2. Add validation of IOPS value in create_volume request

### CODE REVIEW

**Comment by contsto** [comment]
:red_circle: Coverage decreased from [92.5417%] to [91.3919%]

**Comment by contsto** [comment]
:red_circle: Coverage decreased from [92.5417%] to [91.3919%]

**Comment by contsto** [comment]
:red_circle: Coverage decreased from [92.5417%] to [86.1525%]

**Comment by contsto** [comment]
:red_circle: Coverage decreased from [92.5417%] to [86.1525%]

**Comment by contsto** [comment]
:red_circle: Coverage decreased from [92.5417%] to [86.3575%]

**Review by sameshai — APPROVED** [review]

**Review by ambiknai — APPROVED** [review]

**Pull request merged**
