### PR TITLE
Update csi-common version

### PR DESCRIPTION
**Pull request by prankulmahajan**

### CODE REVIEW

**Comment by contsto** [comment]
:thumbsup: Coverage remained same at [93.1853%]

**Comment by contsto** [comment]
:red_circle: Coverage decreased from [93.1853%] to [93.1029%]

**Comment by contsto** [comment]
:red_circle: Coverage decreased from [93.1853%] to [92.0441%]

**Comment by contsto** [comment]
:red_circle: Coverage decreased from [93.1853%] to [92.3265%]

**Review by GunaKKIBM — APPROVED** [review]
lgtm

**Review by sameshai — APPROVED** [review]

**Pull request merged**
